#!/usr/bin/env bash
# Generate browser-visible, content-versioned URLs from the verified asset lock.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLIC="$ROOT/public"
# shellcheck source=assets.lock.sh
source "$ROOT/scripts/assets.lock.sh"

sha256_file(){
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print tolower($1)}'
  elif command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print tolower($1)}'
  elif command -v openssl >/dev/null 2>&1; then openssl dgst -sha256 "$1" | awk '{print tolower($NF)}'
  else echo "No SHA-256 tool found" >&2; return 1
  fi
}

versioned(){
  printf '"%s?v=%s"' "$1" "$2"
}

optional_versioned(){
  local path="$1" public_path="$2"
  if [ -s "$path" ]; then
    versioned "$public_path" "$(sha256_file "$path")"
  else
    printf 'null'
  fi
}

TOOLS_JSON="$(optional_versioned "$PUBLIC/images/tools9p.json" "images/tools9p.json")"
PREINSTALLED_STATE="$(optional_versioned "$PUBLIC/images/alpine-preinstalled.bin" "images/alpine-preinstalled.bin")"
PREINSTALLED_META="$(optional_versioned "$PUBLIC/images/alpine-preinstalled.json" "images/alpine-preinstalled.json")"
TMP="$PUBLIC/asset-manifest.js.tmp"

{
  echo "/* Generated by scripts/generate-asset-manifest.sh. Do not edit manually. */"
  echo "globalThis.BROWSEROS_ASSETS = Object.freeze({"
  printf '  "libv86": '; versioned "vendor/libv86.js" "$LIBV86_SHA256"; echo ","
  printf '  "wasm": '; versioned "vendor/v86.wasm" "$V86_WASM_SHA256"; echo ","
  printf '  "bios": '; versioned "vendor/seabios.bin" "$SEABIOS_SHA256"; echo ","
  printf '  "vgaBios": '; versioned "vendor/vgabios.bin" "$VGABIOS_SHA256"; echo ","
  printf '  "buildrootIso": '; versioned "images/linux.iso" "$BUILDROOT_ISO_SHA256"; echo ","
  printf '  "alpineIso": '; versioned "images/alpine.iso" "$ALPINE_ISO_SHA256"; echo ","
  printf '  "alpineKernel": '; versioned "images/alpine-vmlinuz-virt" "$ALPINE_KERNEL_SHA256"; echo ","
  printf '  "alpineInitramfs": '; versioned "images/alpine-initramfs-virt" "$ALPINE_INITRAMFS_SHA256"; echo ","
  printf '  "alpineVersion": "%s",\n' "$ALPINE_RELEASE"
  echo '  "tools9pBase": "images/tools9p",'
  printf '  "tools9pJson": %s,\n' "$TOOLS_JSON"
  printf '  "preinstalledState": %s,\n' "$PREINSTALLED_STATE"
  printf '  "preinstalledStateMeta": %s\n' "$PREINSTALLED_META"
  echo "});"
} > "$TMP"

mv -f "$TMP" "$PUBLIC/asset-manifest.js"
echo "Generated $PUBLIC/asset-manifest.js"
